/** Production / AVL / ERP taglines — random login subtitle. */
export const LOGIN_TAGLINES: string[] = [
  // Mixinary / brand
  "Mixinary: where the cue always hits.",
  "High quality production. Medium quality passwords.",
  "Mixing signals since… well, since you logged in.",
  "ERP so smooth it could be a crossfade.",
  "Your BOM called. It wants less drama.",
  "Projects, parts, and punchlines.",
  "We put the ‘pro’ in procurement.",
  "AVL: Always Verifying Lines.",
  "Built for installs that don’t install themselves.",
  "Less spreadsheet. More showtime.",

  // Production life
  "Coffee first. Cue second. Panic optional.",
  "Trust the plan. Verify the backup.",
  "If it works on the truck, ship it.",
  "Tape is a lifestyle.",
  "Never trust a green light without a meter.",
  "Call time is a suggestion… said nobody ever.",
  "The show must go on. The BOM must go out.",
  "Gaffers: the real project managers.",
  "Please hold for the TD.",
  "We’re not late. We’re creatively delayed.",
  "One more take. Said 14 times.",
  "Quiet on set. Loud in Slack.",
  "Load-in: cardio with a purpose.",
  "Strike is just load-in in reverse… theoretically.",
  "Soft open. Hard deadlines.",
  "Tech rehearsal: where optimism goes to die.",
  "Dress rehearsal with undressed cables.",
  "House lights up. Spirits… loading.",
  "Intermission for your inbox.",
  "Encore for the PO that finally posted.",

  // AV / video / lighting
  "Resolution: 4K. Patience: 240p.",
  "Frame-accurate feelings.",
  "Sync or swim.",
  "Genlock your expectations.",
  "HDMI: High Drama Multimedia Interface.",
  "SDI: Seriously Don’t Interrupt.",
  "NDI: Now Distributing Issues.",
  "Latency is just dramatic timing.",
  "Blackout: the original dark mode.",
  "DMX: Don’t Mention XLR… wait, do.",
  "XLR: eXtra Long Reasons to coil carefully.",
  "BNC: Basically Never Connected right the first time.",
  "Cat6: Catching All Trouble, 6 days a week.",
  "Fiber: fragile ego energy.",
  "Patchbay of dreams.",
  "Matrix switcher, matrix of feelings.",
  "Scaler: making small problems look big.",
  "EDID: Everyone Disagrees; It’s Drama.",
  "HDCP: Highly Dramatic Content Problems.",
  "No signal? No problem. Just kidding: problem.",
  "Clip warning: your weekend.",
  "Gain staging your career.",
  "Phantom power for phantom deadlines.",
  "48V of pure motivation.",
  "Mic check 1-2. Sanity check 3-4.",
  "RF: Random Frequencies.",
  "IEM: In-Ear Meltdown prevention.",
  "Wireless: wires, elsewhere.",
  "Line array: lined up and ready to array your day.",
  "Subwoofer: feeling the budget.",
  "LED wall: expensive screensaver.",
  "Pixel pitch: how close you’ll get to perfection.",
  "Mapping: cartography for light.",
  "Timecode: the only clock that matters.",
  "LTC: Long Timecode Complaints.",
  "Word clock: say it like you mean it.",
  "Multiview: seeing everything, fixing nothing yet.",
  "ISO recording: isolation, but make it productive.",
  "Program / preview: hope / reality.",
  "Tally light: you’re on. Don’t blink.",
  "Return feed: returning the favor of chaos.",
  "Confidence monitor: ironically named.",
  "QLab: cue lab, not cue lounge.",
  "Macros: automation with ambition.",
  "Snapshot: save early, save often, save the show.",

  // ERP / BOM / procurement puns
  "BOM voyage.",
  "Bill of materials. Bill of rights. Bill of “why is this backordered?”",
  "SKU? I barely know you.",
  "Part number: the love language of purchasing.",
  "MSRP: Mildly Surprising Retail Price.",
  "Quote unquote… still waiting on the quote.",
  "Override %: because math has feelings too.",
  "Out of pocket: in of stress.",
  "PO: Please Order. Also: Pretty Overdue.",
  "Lead time: the plot twist.",
  "Backorder: the sequel nobody asked for.",
  "Receiving: believing.",
  "Warehouse: where parts go to find themselves.",
  "Ship date: a romantic fiction genre.",
  "Tracking number: emotional support digits.",
  "Vendor account: friendship with invoices.",
  "Net 30: net stress for 30 days.",
  "Three-way match: PO, invoice, and destiny.",
  "Catalog scrape: AI, but make it shopping.",
  "Line item therapy.",
  "Section headers: emotional support headings.",
  "Sort order: chaos, alphabetized.",
  "Default override: default overdrive.",
  "Margin call… but for cables.",
  "Cost plus attitude.",
  "UOM: Units of Mystery.",
  "Qty: quantum of ‘are we sure?’",
  "Spare kit: future-you’s thank-you note.",
  "Consumables: consumed by the schedule.",
  "Serialized: drama with a serial number.",
  "RMA: Return My Attitude.",
  "Freight: the silent budget killer.",
  "Drop ship: drop everything and ship.",
  "Expedite fee: paying for yesterday.",
  "Partial receive: partial relief.",
  "Closed PO: rare Pokémon.",
  "Draft status: living my truth.",
  "On hold: on brand.",
  "Archived: out of sight, still in feelings.",

  // Project management
  "Scope creep: the original horror franchise.",
  "Change order: change, but make it official.",
  "Kickoff: coffee and courage.",
  "Milestone: a stone you trip over.",
  "Critical path: critically path-etic sometimes.",
  "Dependencies: emotionally attached tasks.",
  "Gantt chart: calendar with commitment issues.",
  "Standup: sit down and talk about standing up.",
  "Sprint: run toward the demo.",
  "Backlog: the attic of ambitions.",
  "Blocked: by life, by parts, by Wi‑Fi.",
  "Unblock me like you unblock a drain.",
  "Assignee: named and slightly blamed.",
  "Due date: due diligence’s cousin.",
  "Overdue: fashionably late, operationally loud.",
  "Priority: P0 energy, P3 resources.",
  "Risk register: the worry guestbook.",
  "Mitigation: tape and hope.",
  "Stakeholder: holding stakes and opinions.",
  "Alignment meeting: aligning calendars first.",
  "Parking lot: where ideas go to sunbathe.",
  "Action item: action figure, missing accessories.",
  "Follow-up: the sequel to talking.",
  "Circling back: orbital mechanics for email.",
  "Touching base: baseball metaphors in ERP.",
  "Synergy: Scrabble word, corporate spice.",
  "Bandwidth: what we pretend to have.",
  "Capacity: cups of coffee remaining.",
  "Resource leveling: nap scheduling.",
  "Baseline: the lie we agreed to.",

  // Install / field
  "Job site: office with better boots.",
  "Site survey: sightseeing with a tape measure.",
  "Rough-in: rough day, in progress.",
  "Trim out: finishing touches and finishing patience.",
  "Punch list: the list that punches back.",
  "As-built: as-hoped, edited.",
  "Redlines: the spicy drawings.",
  "RFI: Request For Interpretation.",
  "Submittal: submit all hope ye who enter.",
  "Commissioning: turning it on on purpose.",
  "Burn-in: leave it on until it behaves.",
  "Label maker: the real MVP.",
  "Cable management: adulting for wires.",
  "Velcro: temporary forever.",
  "Zip ties: commitment issues.",
  "Service loop: service with a loop of luck.",
  "Ceiling tile: the trapdoor of destiny.",
  "Lift rental: elevating the conversation.",
  "PPE: Pretty Please Equipment.",
  "Hot work: cool heads.",
  "Lockout/tagout: boundaries, but for power.",
  "Megger: checking insulation and intentions.",
  "Ton of gear: literally.",
  "Road case: luggage with a union card.",
  "Truck pack: 3D Tetris with liability.",
  "Manifest: list of what’s missing soon.",
  "Advance: advance notice of surprises.",
  "Runner: cardio department.",
  "Crafty: snacks are a critical path.",
  "Per diem: per dream of a hot meal.",

  // Audio jokes
  "Check one. Check two. Check ego.",
  "Feedback: the unwanted opinion.",
  "Ringing out the room. Ringing out the stress.",
  "Compressor: squashing peaks and dreams.",
  "Limiter: knowing your limits.",
  "EQ: Emotional Quotient for frequencies.",
  "High-pass: letting go of the bass-less worries… wait.",
  "Low-cut: cutting the drama.",
  "Reverb: making mistakes sound bigger.",
  "Delay: artistic lateness.",
  "Bus: where channels go to socialize.",
  "Send/return: relationship goals for FX.",
  "Insert: dramatic entrance.",
  "Solo: main character energy.",
  "Mute: self-care for channels.",
  "PFL: Pre-Fight Listen.",
  "AFL: After Feelings Listen.",
  "Talkback: talking back, professionally.",
  "Clear-com: clear communication, unclear caffeine.",
  "Party line: group chat with headsets.",
  "IFB: Interrupted For Briefings.",
  "Stage left: audience right, life wrong.",
  "Downstage: emotionally available.",
  "Upstage: stealing focus and snacks.",

  // Lighting jokes
  "Gel: mood in a sheet.",
  "Gobo: pattern interrupter.",
  "Iris: eyes on the prize.",
  "Dimmer: soft landings for watts.",
  "Cue stack: stacked emotions.",
  "Blind mode: editing without judgment… mostly.",
  "Park: parking lights like parking feelings.",
  "Fixture profile: LinkedIn for lights.",
  "Addressing: finding yourself in the universe (0–512).",
  "Universe: and everything in it, on one cable.",
  "Art-Net: art, net, and mild panic.",
  "sACN: streaming A Certain Nervousness.",
  "RDM: Remote Device Moodiness.",
  "Strobe: blink and you’ll miss the budget.",
  "Fog machine: atmosphere and HR concerns.",
  "Hazer: soft focus for reality.",
  "House plot: fiction based on a true venue.",

  // Software / ERP life
  "Save early. Save often. Save the BOM.",
  "Autosave: trust issues, healed slightly.",
  "Ctrl+Z: the undo of adulthood.",
  "Refresh: turning it off and on again, spiritually.",
  "Cache: where bugs go to vacation.",
  "Cookie: not the snack you wanted.",
  "Session expired: like milk, but digital.",
  "2FA: two factors of ‘where’s my phone?’",
  "SSO: So Satisfying… Occasionally.",
  "Magic link: witchcraft with email.",
  "Password reset: character development.",
  "Role-based access: know your role.",
  "Admin: with great power comes great tickets.",
  "Read-only: look, don’t touch the vibes.",
  "Audit log: receipts, forever.",
  "Dark mode: for late truck packs.",
  "Light mode: for early call times.",
  "Loading… like the truck.",
  "404: part not found (check the aisle).",
  "500: server had a moment.",
  "Timeout: take a breath.",
  "Retry: the unofficial company motto.",
  "Deploy Friday: live dangerously.",
  "Hotfix: hot take, warmer sweat.",
  "Feature flag: maybe later energy.",
  "Tech debt: the installment plan.",
  "Legacy system: haunted spreadsheet.",
  "Migration: moving house with databases.",
  "Schema: the blueprint of feelings.",
  "Null: the void where a value should be.",
  "Undefined: like the ship date.",
  "NaN: Not a Number, Not a Problem? Wrong.",
  "Boolean: true story / false hope.",
  "Integer: whole vibes only.",
  "Float: floating the idea of floating point.",
  "Commit: relationship status for code.",
  "Push: to production, to the limit.",
  "Pull request: asking nicely.",
  "Merge conflict: group project energy.",
  "Main branch: do not disturb.",
  "Staging: dress rehearsal for servers.",
  "Prod: the real stage.",
  "Rollback: time travel for cowards (smart cowards).",
  "Monitor: watching watches watch things.",
  "Alert fatigue: crying wolf.exe.",
  "Uptime: the vibe we chase.",
  "SLA: Slightly Loose Agreements.",
  "KPI: Key Panic Indicators.",
  "OKR: Objectives & Kaboom Results.",
  "ROI: Return On Insomnia.",

  // Mixinary-specific / install culture
  "Rack elevation: climbing the corporate ladder, vertically.",
  "Elevation drawing: drawing elevated expectations.",
  "Single-line: simple story, complex truth.",
  "Shop drawing: shopping list with geometry.",
  "Cut sheet: paper cuts and product cuts.",
  "Spec book: bedtime reading for PMs.",
  "Owner’s manual: owner’s suggestion.",
  "Warranty: war, then anty… wait.",
  "Extended warranty: extended arguments.",
  "Spare stock: stocked for the unexpected expected.",
  "Loaner: temporary friendship.",
  "Demo unit: demo or die.",
  "Proof of concept: proof of chaos.",
  "Pilot: flying blind with instrumentation.",
  "Go-live: go loud.",
  "Soft launch: hard land.",
  "Hypercare: care, but hyper.",
  "Stabilization: tape and meetings.",
  "Closeout: closing tabs and chapters.",
  "O&M manuals: Operation & Mild confusion.",
  "Training day: teach, pray, repeat.",
  "Knowledge transfer: telepathy, unpaid.",
  "Handover: handing over the hot potato.",
  "Acceptance: finally.",
  "Sign-off: penmanship as a service.",
  "Certificate of completion: participation trophy for buildings.",
  "As-built package: package deal of reality.",
  "Record drawing: drawing of the record we set.",
  "Lessons learned: lessons earned.",
  "Postmortem: the show after the show.",

  // Wordplay / memes
  "It’s not a bug. It’s a live event.",
  "Works on my console.",
  "Have you tried reseating the vibe?",
  "Unplug it. Count to 10. Replug your life.",
  "That’s a tomorrow problem. Tomorrow called: no.",
  "Running on fumes and firmware.",
  "Firmware: firm about its ware.",
  "Software: soft about its deadlines.",
  "Hardware: hard truths.",
  "Middleware: middle child energy.",
  "Cloud: someone else’s rack.",
  "On-prem: on-brand for control freaks.",
  "Hybrid: the diplomatic answer.",
  "Air gap: personal space for networks.",
  "VLAN: Very Lonely Area Network.",
  "VPN: Very Private Nervousness.",
  "DNS: Did Not Start (until you fixed it).",
  "DHCP: Dynamic Host Chaos Protocol.",
  "IP conflict: identity crisis.",
  "Gateway: the bouncer.",
  "Firewall: spicy router.",
  "Packet loss: emotional baggage.",
  "Jitter: coffee in network form.",
  "Bitrate: how fast the bits rate your day.",
  "Codec: code for ‘why won’t it play?’",
  "Container: for apps and leftover catering.",
  "Orchestration: conducting microservices like a pit.",
  "Kubernetes: Greek for ‘please help’.",
  "Docker: ships containers, not scenery… usually.",
  "YAML: Yet Another Meeting Language.",
  "JSON: JavaScript Object Notions.",
  "CSV: Comma Separated Vibes.",
  "Excel: the original ERP.",
  "Pivot table: pivoting your personality.",
  "VLOOKUP: very looking up.",
  "Macro-enabled: trust issues enabled.",
  "Protected sheet: boundaries.",
  "Circular reference: this meeting.",
  '#REF!: your weekend plans.',
  "Conditional formatting: mood lighting for cells.",
  "Freeze panes: freeze frame for columns.",
  "Filter view: rose-colored glasses, data edition.",
  "Named range: celebrity cells.",
  "Data validation: trust but verify.",
  "What-if analysis: spiraling, professionally.",
  "Goal seek: seeking goals and snacks.",
  "Solver: solving for X and for peace.",
  "Power Query: power hour for data.",
  "Power BI: power by caffeine.",
  "Dashboard: cars optional.",
  "Widget: bite-sized anxiety.",
  "KPI tile: tiny judge.",
  "Sparkline: spark joy, line chart.",
  "Heatmap: spicy geography.",
  "Funnel chart: where leads go to drip.",
  "Waterfall chart: cascading regrets.",
  "Burn-down: also a personal brand.",
  "Velocity: speed of tickets, not trucks.",
  "Story points: fiction, numbered.",
  "Epic: long story short… it’s long.",
  "User story: once upon a requirement.",
  "Acceptance criteria: friendship criteria for tickets.",
  "Definition of done: done-ish.",
  "WIP limit: wishful thinking limit.",
  "Kanban: visual procrastination.",
  "Swimlane: lanes for tasks that can’t swim.",
  "Bottleneck: the neck of the bottle of time.",
  "Throughput: putting through the work.",
  "Cycle time: time of the cycle of ‘almost’.",
  "Lead time: leading you on.",
  "Takt time: German for ‘keep up’.",
  "Kaizen: continuous improvement, continuous coffee.",
  "Five whys: four too many.",
  "Root cause: the root of all causes.",
  "Fishbone: diagram with bones to pick.",
  "Pareto: 80% of jokes, 20% of setup.",
  "Murphy’s law: AV’s constitution.",
  "Sod’s law: Murphy’s cousin on tour.",
  "Hope is not a strategy. Hope is a backup plan’s backup.",
  "Plan B: the real Plan A.",
  "Contingency: content agency for chaos.",
  "Redundancy: saying it twice because it matters.",
  "Failover: failing over to Plan B gracefully.",
  "Hot spare: spare that’s emotionally available.",
  "Cold spare: spare in the truck, cold.",
  "N+1: always plus one, like a wedding.",
  "2N: twice the gear, twice the fun.",
  "MTBF: Mean Time Between Feelings.",
  "MTTR: Mean Time To Rejoice (after repair).",
  "SLA breach: fashionably late to the contract.",
  "Escalation: elevating the ticket and the pulse.",
  "Severity 1: everyone knows.",
  "Severity 2: almost everyone knows.",
  "Severity 3: Slack knows.",
  "P1: please one more miracle.",
  "War room: meeting room with worse snacks.",
  "Bridge call: bridging gaps and patience.",
  "Screen share: sharing is caring, and scary.",
  "You’re on mute: the national anthem of remote work.",
  "Can you see my screen?: philosophical.",
  "Let’s take this offline: let’s never speak of this.",
  "Quick sync: neither quick nor sync’d.",
  "EOD: End Of Daydreams.",
  "COB: Close Of Business… or Close Of Brain.",
  "ASAP: As Soon As Possible, Apparently.",
  "FYI: For Your Interest / Anxiety.",
  "TBD: To Be Determined / To Be Delayed.",
  "TBA: To Be Announced / To Be Avoided.",
  "ETA: Estimated Time of Arrival of answers.",
  "EOD Friday: mythical creature.",
  "Monday energy: buffering…",
  "Tuesday: the real Monday.",
  "Hump day: over the hump, under the deadline.",
  "Thursday: Friday’s understudy.",
  "Friday deploy: living on the edge of the stage.",
  "Weekend: read-only mode.",
  "On-call: emotionally on-call.",
  "PagerDuty: pager, duty, dread.",
  "Ack the alert. Pack the truck.",
  "Silence the alert. Don’t silence the issue.",
  "Runbook: the cookbook for fires.",
  "Playbook: plays for when the play goes wrong.",
  "Incident: coincidence with an audience.",
  "Post-incident review: storytime with scars.",
  "Blameless culture: blame the process, hug the person.",
  "Customer impact: the plot.",
  "Internal only: secret show.",
  "Public status page: honesty as a service.",
  "Degraded performance: vibes: mid.",
  "Partial outage: partially our rage.",
  "Full outage: full send… of apologies.",
  "Maintenance window: the window we climb through.",
  "Change freeze: frozen in fear, officially.",
  "Blackout period: no deploys, all snacks.",
  "Code freeze: winter for repositories.",
  "Feature complete: feature compete with bugs.",
  "Bug bash: party with a purpose.",
  "Regression: progress, but backward.",
  "Flaky test: flake, but make it CI.",
  "Green build: go energy.",
  "Red build: stop and think.",
  "Yellow build: caution: vibes unstable.",
  "Coverage: blanket for code.",
  "Lint: cleaning lint from your logic.",
  "Format on save: manners for markup.",
  "Prettier: prettier code, prettier you.",
  "ESLint: emotionally supportive lint.",
  "TypeScript: types for the typed and the tired.",
  "Any: the escape hatch of shame.",
  "Unknown: healthier than any.",
  "Never: TypeScript’s dramatic flair.",
  "Strict mode: no fun… more fun later.",
  "Optional chaining: ?. maybe.",
  "Nullish coalescing: ?? coping.",
  "Async/await: waiting professionally.",
  "Promise: I pinky-promise this resolves.",
  "Callback hell: circle of callback life.",
  "Race condition: racing to be wrong first.",
  "Deadlock: two locks, zero keys, one meeting.",
  "Memory leak: forgetting to forget.",
  "GC pause: garbage collection, emotional collection.",
  "OOM: Out Of Memory / Out Of Motivation.",
  "Stack overflow: too deep, too soon.",
  "Heap: a pile of problems.",
  "Core dump: dumping cores and tea.",
  "Segfault: segmentation of your afternoon.",
  "Kernel panic: the OS had a feeling.",
  "Blue screen: classic cinema.",
  "Spinning beachball: macOS meditation.",
  "Hourglass: vintage loading.",
  "Skeleton screen: bones of the UI.",
  "Shimmer: loading, but make it fashion.",
  "Empty state: zen garden for apps.",
  "Error boundary: emotional boundary for React.",
  "Hydration mismatch: water and HTML, mixed poorly.",
  "SSR: Server-Side Reality check.",
  "CSR: Client-Side Roulette.",
  "ISR: Incremental Static Regret.",
  "Edge: living on it.",
  "CDN: Content Delivery Naps.",
  "Cache hit: dopamine.",
  "Cache miss: plot twist.",
  "TTL: Time To Live / Time To Leave.",
  "Idempotent: same result, same joke.",
  "Eventually consistent: eventually fine.",
  "Strong consistency: strong opinions.",
  "ACID: database personality type.",
  "BASE: Basically Available, Soft state, Eventual… coffee.",
  "Transaction: commitment issues resolved briefly.",
  "Rollback segment: segment of regret.",
  "Foreign key: keys to someone else’s table.",
  "Primary key: main character energy for rows.",
  "Index: shortcuts for queries and for life.",
  "Full table scan: reading the whole book for one sentence.",
  "N+1 query: death by a thousand selects.",
  "ORM: Object-Relational Mood.",
  "Raw SQL: living dangerously with strings.",
  "Migration down: time travel ticket.",
  "Seed data: planting the vibes.",
  "Fixture: test data / lighting device / both.",
  "Mock: pretend friend for tests.",
  "Stub: short friend for tests.",
  "Spy: watching your functions.",
  "Snapshot test: polaroid of UI.",
  "E2E: End-to-End / End-to-Emotions.",
  "Unit test: tiny trust falls.",
  "Integration test: group project that works.",
  "Smoke test: if it smokes, stop.",
  "Canary: bird in the coal mine of deploys.",
  "Blue/green: fashion colors for releases.",
  "A/B test: arguing with data.",
  "Feature toggle: light switch for risk.",
  "Kill switch: big red button energy.",
  "Circuit breaker: boundaries for services.",
  "Backoff: backing off, exponentially.",
  "Retry storm: rain of retries.",
  "Thundering herd: everyone at once, like load-in.",
  "Hot path: the path we all take.",
  "Cold start: coffee required.",
  "Warm pool: spa day for instances.",
  "Autoscaling: growing pains, automated.",
  "Right-sizing: Goldilocks for servers.",
  "FinOps: finance meets ops meets feelings.",
  "Cost center: where money goes to network.",
  "Chargeback: charging back the vibe.",
  "Showback: showing the bill gently.",
  "CapEx: capital expense / capital exhaustion.",
  "OpEx: operating expense / operating exhaustion.",
  "TCO: Total Cost of Ownership / Total Cost of ‘Oh no’.",
  "NPV: Net Present Value / Net Present Vibes.",
  "IRR: Internal Rate of Return / Internal Rate of Rage.",
  "Gross margin: marginally gross sometimes.",
  "Net margin: net of the nonsense.",
  "COGS: Cost Of Gear Stuff.",
  "Overhead: what’s over your head, literally and fiscally.",
  "Burden rate: burden, rated.",
  "Billable: the dream.",
  "Non-billable: the reality.",
  "Utilization: how used you feel.",
  "Write-off: writing off the day.",
  "Accrual: accruing stress.",
  "Deferred revenue: deferred joy.",
  "Recognized revenue: recognized at last.",
  "Close the books: close the laptop.",
  "Month-end: seasonal event.",
  "Year-end: boss fight.",
  "Audit season: festive anxiety.",
  "Tax: the original subscription.",
  "Invoice: love letter from accounting.",
  "Credit memo: apology in currency.",
  "Debit: dramatic entrance of money leaving.",
  "Ledger: the story of the money.",
  "Journal entry: diary of dollars.",
  "Reconciliation: making up with the bank.",
  "Variance: the plot hole in the budget.",
  "Forecast: weather for money.",
  "Budget: fan fiction about spending.",
  "Actuals: the autobiography.",
  "Pipeline: pipes full of deals and dreams.",
  "Funnel: where deals drip.",
  "Conversion: converting hope to cash.",
  "Churn: the sad spin cycle.",
  "Retention: keeping friends and customers.",
  "Upsell: up, sell, repeat.",
  "Cross-sell: selling across the aisle.",
  "Land and expand: real estate for SaaS.",
  "POC to production: character arc.",
  "Pilot to rollout: takeoff to cruising altitude.",
  "GA: Generally Available / Generally Anxious.",
  "Beta: better than alpha, worse than done.",
  "Alpha: first draft energy.",
  "Dogfood: eating your own cooking.",
  "Ship it: famous last words.",
  "Launch day: birth day for features.",
  "Press release: releasing the press… and the stress.",
  "Changelog: diary of differences.",
  "Release notes: footnotes for bravery.",
  "Breaking change: break a leg… and an API.",
  "Deprecation: saying goodbye slowly.",
  "EOL: End Of Life / End Of Laughs.",
  "Sunset: beautiful ending for a product.",
  "Legacy support: supporting ghosts.",
  "Backward compatible: looking back, kindly.",
  "Forward compatible: optimistic compatibility.",
  "Polyfill: filling the gaps of the past.",
  "Shim: thin layer of hope.",
  "Adapter: making misfits fit.",
  "Facade: pretty face for a messy system.",
  "Proxy: standing in, standing tall.",
  "Gateway pattern: pattern for getting in.",
  "Sidecar: motorcycle energy for services.",
  "Service mesh: mesh well with others.",
  "Event-driven: driven by events and espresso.",
  "Message queue: waiting room for payloads.",
  "Pub/sub: publish your feelings, subscribe carefully.",
  "Webhook: hooking the web, gently.",
  "Polling: asking again and again.",
  "Long poll: long conversation.",
  "WebSocket: socket to me.",
  "gRPC: go really (pretty) quick… supposedly.",
  "REST: sleep, and also APIs.",
  "GraphQL: ask for what you want, get what you deserve.",
  "SOAP: clean protocol, messy memories.",
  "RPC: Remote Procedure Chaos.",
  "API key: key to the kingdom / key to the incident.",
  "OAuth: Oh Auth.",
  "JWT: Just Wait, Token.",
  "Bearer token: bear with us.",
  "Refresh token: refresh your spirit.",
  "Scope: keep it tight.",
  "Claim: claim your identity.",
  "Audience: who this token is for / who this show is for.",
  "Issuer: who said so.",
  "Subject: who it’s about.",
  "Nonce: once, with feeling.",
  "CSRF: Cross-Site Request Forgery / Cross-Site Request Feelings.",
  "XSS: Cross-Site Scripting / Cross-Site Screaming.",
  "SQLi: SQL injection / SQL indigestion.",
  "CORS: Cross-Origin Resource Sharing / Cross-Origin Resource Stress.",
  "CSP: Content Security Policy / Content Security Please.",
  "HSTS: HTTP Strict Transport Security / HTTP Strict Transport Sanity.",
  "TLS: Transport Layer Security / Transport Layer Serenity.",
  "mTLS: mutual TLS / mutual trust issues resolved.",
  "Cert expiry: birthday for outages.",
  "Let’s Encrypt: let’s encrypt and let’s go.",
  "Self-signed: signing your own yearbook.",
  "CA: Certificate Authority / Caffeine Authority.",
  "Pinning: pinning hopes on pins.",
  "Revocation: taking it back.",
  "OCSP: Online Certificate Status Panic.",
  "Zero trust: trust issues as architecture.",
  "Least privilege: least drama access.",
  "Break glass: emergency vibes.",
  "Secret rotation: rotating secrets like tires.",
  "Vault: where secrets go to feel safe.",
  "Env var: environment variable / environmental hazard if leaked.",
  ".env.local: local legends only.",
  "gitignore: ignoring problems strategically.",
  "README: read me, please.",
  "TODO: tomorrow’s personality.",
  "FIXME: honesty in comments.",
  "HACK: temporary forever.",
  "XXX: marks the spot of shame.",
  "WTF: Wide Technical Feedback.",
  "LGTM: Looks Good To Merge / Looks Good To Me.",
  "Nit: tiny opinion, big energy.",
  "Bike shed: arguing about paint.",
  "Yak shave: shaving yaks between cues.",
  "Rubber duck: debugging with a friend who doesn’t judge.",
  "Stack Overflow: copying with conviction.",
  "ChatGPT: pair programmer who never sleeps.",
  "Copilot: copiloting into production.",
  "AI review: robots have opinions now.",
  "Human in the loop: please keep the human.",
  "Hallucination: AI improvisation.",
  "Prompt engineering: writing spells.",
  "Temperature: creativity dial / thermostat for models.",
  "Tokens: coins for thoughts.",
  "Context window: short-term memory, long-term ambitions.",
  "Embedding: vibes as vectors.",
  "RAG: Retrieval-Augmented Guessing… carefully.",
  "Fine-tune: fine-tuning your patience.",
  "Eval: grading the robot.",
  "Guardrail: rails for the model, and for you.",
  "Safety layer: seatbelt for sentences.",
  "Tool use: robots with hands.",
  "Agent: autonomous ambition.",
  "Multi-agent: committee of robots.",
  "Orchestrator: conductor of the silicon pit.",
  "Workflow: work that flows… eventually.",
  "Human approval: the VIP gate.",
  "Audit trail: breadcrumbs with timestamps.",
  "Compliance: complying and complaining.",
  "SOC 2: socks too, and controls.",
  "ISO: in search of order.",
  "GDPR: good data privacy reflexes.",
  "PII: Please Investigate Identity.",
  "Encryption at rest: resting securely.",
  "Encryption in transit: traveling securely.",
  "Hash: breakfast and cryptography.",
  "Salt: seasoning for passwords.",
  "Pepper: spicy secrets.",
  "Bcrypt: slow on purpose.",
  "Argon2: cooler bcrypt.",
  "MFA: Multi-Factor Annoyance (that saves you).",
  "Passkey: key without the password pain.",
  "Biometric: face as password.",
  "Session fixation: stuck in a session.",
  "Privilege escalation: climbing the org chart illegally.",
  "Penetration test: authorized mischief.",
  "Red team: playing villain for good.",
  "Blue team: defense wins championships.",
  "Purple team: collaboration couture.",
  "Tabletop exercise: RPGs for incidents.",
  "DR: Disaster Recovery / Dramatic Reboot.",
  "BCP: Business Continuity Plan / Bring Coffee Please.",
  "RTO: Recovery Time Objective / Recovery Time Optimism.",
  "RPO: Recovery Point Objective / Recovery Point Oh-no.",
  "Backup: the quiet hero.",
  "Restore test: trust but verify the backup.",
  "3-2-1: backups, not countdown… also countdown.",
  "Offsite: off-site, on-mind.",
  "Immutable backup: can’t edit the past.",
  "Air-gapped backup: personal space for data.",
  "Snapshotting: saying cheese to disks.",
  "Replication: cloning with purpose.",
  "Geo-redundant: redundant across geography and jokes.",
  "Active-active: both sides of the stage lit.",
  "Active-passive: understudy energy.",
  "Quorum: majority rules.",
  "Split brain: two primaries, one headache.",
  "Consensus: agreeing to agree.",
  "Leader election: democracy for databases.",
  "Follower: reading along.",
  "Replica lag: lagging behind emotionally.",
  "Write amplify: writing too much, feeling too much.",
  "Read replica: reading the room, replicated.",
  "Sharding: sharing the load by breaking it.",
  "Partition: walls for data.",
  "Hot spot: popular partition / popular problem.",
  "Rebalance: balancing acts.",
  "Compaction: cleaning house.",
  "Vacuum: Postgres self-care.",
  "Analyze: thinking about the query plan.",
  "Explain: explain yourself, query.",
  "Seq scan: sequential scanning of your patience.",
  "Bitmap index: map of bits and wits.",
  "Join: making tables talk.",
  "Left join: leaving no left row behind… sometimes.",
  "Inner join: intimate tables.",
  "Cross join: chaos cartesian.",
  "Union: united rows.",
  "Distinct: unique snowflakes.",
  "Group by: flocking together.",
  "Having: having standards.",
  "Order by: ordering chaos.",
  "Limit 1: main character only.",
  "Offset: skipping ahead.",
  "Window function: windows into aggregates.",
  "CTE: Common Table Expression / Common Table Escape.",
  "Materialized view: view with commitment issues resolved.",
  "Temp table: temporary housing for rows.",
  "Lock wait: waiting room for locks.",
  "Dead tuple: ghost rows.",
  "Bloat: database winter coat.",
  "Autovacuum: Roomba for relations.",
  "WAL: Write-Ahead Log / Write-Ahead Life.",
  "Checkpoint: save point.",
  "Fsync: flush feelings to disk.",
  "Durable: built to last, like gaff tape.",
  "Consistent: same bit every time.",
  "Available: here for you.",
  "Partition tolerance: tolerant of drama between DCs.",
  "CAP theorem: pick two, cry once.",
  "PACELC: more letters, more feelings.",
  "Idempotency key: key to doing it once.",
  "Exactly once: the myth.",
  "At least once: the reality.",
  "At most once: the gamble.",
  "Poison message: toxic payload.",
  "DLQ: Dead Letter Queue / Dead Letter Quips.",
  "Replay: encore for events.",
  "Outbox: outgoing personality for transactions.",
  "Inbox: incoming tasks.",
  "Saga: long-running drama with compensating actions.",
  "Compensation: making it right.",
  "Orchestration saga: conductor energy.",
  "Choreography saga: dance energy.",
  "Eventual business: eventually shipping.",
  "Domain-driven: driven by the domain and the caffeine.",
  "Bounded context: boundaries, healthy.",
  "Ubiquitous language: saying the same words.",
  "Aggregate: clustered responsibility.",
  "Entity: identity matters.",
  "Value object: vibes without identity.",
  "Repository: where objects live.",
  "Factory: making objects like making cues.",
  "Service layer: service with a smile (and a timeout).",
  "Application service: app-level adulthood.",
  "Domain service: domain-level adulthood.",
  "Infrastructure: the underground of the show.",
  "Hexagonal: ports and adapters and vibes.",
  "Clean architecture: clean as a patched rack.",
  "Onion architecture: layers, tears optional.",
  "MVC: Model-View-Controller / Mildly Very Complicated.",
  "MVVM: extra letters, extra opinions.",
  "Flux: unidirectional feelings.",
  "Redux: reduced chaos, increased boilerplate.",
  "Zustand: state with fewer feelings.",
  "Context API: context for the confused.",
  "Props drilling: digging for data.",
  "Lifting state: gym for React.",
  "Controlled input: control issues, productive.",
  "Uncontrolled input: free spirit form field.",
  "Ref: referring to the DOM politely.",
  "Effect: side effects may include insight.",
  "Memo: remembering so you don’t re-render.",
  "Callback: calling back your functions.",
  "Transition: transitioning UI states like cues.",
  "Suspense: suspenseful loading.",
  "Error boundary: catching feels.",
  "Server component: server main character.",
  "Client component: browser main character.",
  "RSC payload: flight data for UI.",
  "Streaming: shipping HTML like a live feed.",
  "Partial prerender: partially ready, fully ambitious.",
  "Turbopack: turbocharged packing of modules.",
  "Hot reload: hot takes, instantly.",
  "Fast refresh: refreshingly fast.",
  "Cold compile: chilly start.",
  "Tree shake: shaking the dependency tree like a Christmas tree.",
  "Dead code: code that ghosted you.",
  "Bundle size: size matters for the truck and the JS.",
  "Code split: splitting bills and bundles.",
  "Lazy load: lazy, but strategic.",
  "Prefetch: psychic networking.",
  "Preload: loading before the cue.",
  "Preconnect: saying hi early.",
  "DNS prefetch: looking up before looking up.",
  "Critical CSS: critical path styling.",
  "Above the fold: front of house.",
  "Below the fold: understage storage.",
  "CLS: Cumulative Layout Shift / Cumulative Layout Stress.",
  "LCP: Largest Contentful Paint / Largest Contentful Panic.",
  "INP: Interaction to Next Paint / Interaction to Next Patience.",
  "TTI: Time To Interactive / Time To Irritated.",
  "FCP: First Contentful Paint / First Contentful Prayer.",
  "TTFB: Time To First Byte / Time To First Breath.",
  "Web vitals: vital signs for sites.",
  "Perf budget: budgeting for speed.",
  "Flame chart: spicy profiling.",
  "Sample profile: sampling the vibes.",
  "Trace: following the breadcrumbs.",
  "Span: a little stretch of time.",
  "Trace ID: identity for a journey.",
  "Correlation ID: correlating chaos.",
  "Structured logging: logs with manners.",
  "Log level: volume knob for truth.",
  "Debug: where the fun begins.",
  "Info: polite noise.",
  "Warn: yellow flag.",
  "Error: red flag.",
  "Fatal: black flag.",
  "Silly: log level for Fridays.",
  "PII redaction: keeping secrets secret.",
  "Sampling: not all logs make the cut.",
  "Cardinality: too many unique snowflakes.",
  "High cardinality: celebrity metrics.",
  "Histogram: history in bins.",
  "Gauge: mood meter.",
  "Counter: counting blessings and errors.",
  "Rate: how fast it breaks.",
  "SLO: Service Level Objective / Service Level Optimism.",
  "SLI: Service Level Indicator / Service Level Indicator of doom.",
  "Error budget: allowance for oops.",
  "Burn rate: burning the budget and the midnight oil.",
  "Toil: work that works you.",
  "Automation: toil’s natural predator.",
  "Runbook automation: recipes that cook themselves.",
  "ChatOps: operating from the group chat.",
  "Bot: helpful pest.",
  "Webhook relay: relaying the drama.",
  "Status emoji: emotional API.",
  "Thread the needle: and the Slack thread.",
  "Emoji react: democracy.",
  "Pin the message: pinning the plot.",
  "Here: summoning everyone.",
  "Channel topic: foreshadowing.",
  "Huddle: meeting without calendar courage.",
  "Zoom fatigue: classic cinema.",
  "Camera on: vulnerability.",
  "Camera off: mystery.",
  "Virtual background: hiding the truck pack behind you.",
  "Share system audio: sharing the chaos audibly.",
  "Breakout rooms: rooms for breaking out / down.",
  "Waiting room: purgatory lite.",
  "Host controls: power trip, muted.",
  "Co-host: deputy of the call.",
  "Live transcript: closed captions for meetings.",
  "AI summary: summary of summaries.",
  "Action items: items that demand action.",
  "Parking lot notes: valet for ideas.",
  "Decision log: logging decisions like cues.",
  "RACI: Responsible, Accountable, Confused, Informed.",
  "DACI: Driver, Approver, Contributors, Informed / Drama.",
  "RASCI: RACI with Support and extra letters.",
  "Stakeholder map: map of who to ping.",
  "Influence/interest grid: grid of feelings.",
  "Power/interest: politics, charted.",
  "Communication plan: plan to communicate the plan.",
  "RAID log: Risks, Assumptions, Issues, Dependencies / also RAID arrays.",
  "Assumption: the quiet risk.",
  "Constraint: the loud boundary.",
  "Issue: risk that grew up.",
  "Risk score: scoring the scare.",
  "Probability × impact: math for anxiety.",
  "Heat map: where it hurts.",
  "Mitigation owner: owner of making it less bad.",
  "Contingent action: action if the plot twists.",
  "Fallback: falling back gracefully.",
  "Workaround: walking around the problem.",
  "Permanent workaround: temporary forever, promoted.",
  "Technical spike: poking the unknown.",
  "Spike ticket: ticket to explore.",
  "Discovery: discovering how little we knew.",
  "Design doc: documenting the dream.",
  "RFC: Request For Comments / Request For Consensus.",
  "ADR: Architecture Decision Record / Actually Decided, Really.",
  "One-pager: one page, many opinions.",
  "Brief: brief until it isn’t.",
  "Deck: slides as a personality.",
  "Appendix: where truth hides.",
  "Footnote: small text, big implications.",
  "TL;DR: Too Long; Did Review? Rarely.",
  "Executive summary: summary for executives and exhausted people.",
  "Bottom line: the line at the bottom of the vibe.",
  "North star: navigation for product.",
  "South star: the other direction, jokingly.",
  "OKR check-in: checking in on optimism.",
  "Scorecard: report card for grownups.",
  "Traffic light status: RAG, but make it fashion.",
  "RAG status: Red Amber Green / Rarely Actually Green.",
  "Green across the board: mythical.",
  "Yellow: the most honest color.",
  "Red: honesty with urgency.",
  "Blocked on vendor: classic.",
  "Blocked on client: classic-er.",
  "Blocked on ourselves: most honest.",
  "Waiting on parts: the national pastime.",
  "Waiting on drawings: the international pastime.",
  "Waiting on approval: the cosmic pastime.",
  "Approved with comments: approved with homework.",
  "Rejected: character development.",
  "Revise and resubmit: the sequel.",
  "Stamp: the sweetest PDF annotation.",
  "Wet signature: old school cool.",
  "E-sign: new school cool.",
  "DocuSign: documentary of signing.",
  "Counter-sign: signing the other way.",
  "Fully executed: fully adult.",
  "Effective date: when it starts mattering.",
  "Term: how long we’re friends contractually.",
  "Renewal: friendship renewal.",
  "Auto-renew: trap with a calendar.",
  "Opt-out: the escape hatch.",
  "Opt-in: enthusiastic consent for emails.",
  "Unsubscribe: boundary setting.",
  "Newsletter: letters that never end.",
  "Digest: chewing the news slowly.",
  "Notification storm: weather alert for apps.",
  "Do Not Disturb: healthy.",
  "Focus mode: theater etiquette for phones.",
  "Inbox zero: zen.",
  "Inbox infinity: more common.",
  "Snooze: postponing feelings.",
  "Starred: emotional bookmarks.",
  "Archive: outbox for memories.",
  "Spam: the other stage.",
  "Phishing: fishing for credentials.",
  "Spear phishing: targeted fishing.",
  "Whaling: phishing for executives.",
  "Social engineering: theater for hackers.",
  "Pretexting: improv with malice.",
  "Baiting: leaving USB drama on the ground.",
  "Tailgating: following into the venue / the building.",
  "Badge access: identity, clipped on.",
  "Visitor badge: temporary identity.",
  "Escort required: buddy system for buildings.",
  "NDA: Non-Disclosure Agreement / Non-Dramatic Agreement… unlikely.",
  "MSA: Master Service Agreement / Master Stress Agreement.",
  "SOW: Statement Of Work / Statement Of Worry.",
  "CO: Change Order / Chaos Order.",
  "PCO: Potential Change Order / Potential Chaos Order.",
  "CCD: Construction Change Directive / Construction Change Drama.",
  "ASI: Architect’s Supplemental Instructions / Also Still Incomplete.",
  "Bulletin: news flash from design.",
  "Addendum: adding to the plot.",
  "Alternate: Plan B in the bid.",
  "Allowance: allowance for unknowns.",
  "Unit price: price per unit of chaos.",
  "Lump sum: lump of money, sum of risks.",
  "GMP: Guaranteed Maximum Price / Guaranteed Maximum Pressure.",
  "T&M: Time & Materials / Time & Miracles.",
  "NTE: Not To Exceed / Need To Escape.",
  "Retainage: retention of cash and breath.",
  "Progress billing: billing for progress and vibes.",
  "Schedule of values: values, scheduled.",
  "Pay app: application for payment / application of patience.",
  "Lien waiver: waving goodbye to liens.",
  "Conditional waiver: waving with conditions.",
  "Unconditional love… and waivers.",
  "Notice to proceed: green light on paper.",
  "Substantial completion: mostly done, emotionally.",
  "Final completion: actually done.",
  "Warranty walk: walking the talk.",
  "11-month walk: anniversary of the install.",
  "Callback: service encore.",
  "Service ticket: ticket to ride the elevator again.",
  "Truck roll: rolling out.",
  "No problem found: the scariest ticket status.",
  "Could not reproduce: ghost story.",
  "Works as designed: designer flex.",
  "User error: sometimes true, always delicate.",
  "PEBKAC: Problem Exists Between Keyboard And Chair.",
  "ID-10-T: classic support humor.",
  "Layer 8: the human layer.",
  "PICNIC: Problem In Chair, Not In Computer.",
  "Have you tried turning it off and on again?: the liturgy.",
  "Is it plugged in?: the catechism.",
  "Is it muted?: audio edition.",
  "Is input selected?: video edition.",
  "Is the breaker on?: electrical edition.",
  "Is the network up?: everyone’s edition.",
  "Check the obvious: check the universe.",
  "Start at layer 1: copper and courage.",
  "Follow the signal: follow your heart, then the schematic.",
  "Trust, but verify with a meter.",
  "Measure twice. Cut once. Label thrice.",
  "Coil with the prayer of future-you.",
  "Leave a service loop for future kindness.",
  "Dress the cables like you mean it.",
  "A clean rack is a quiet mind.",
  "A labeled port is a love letter.",
  "Documentation is a gift to strangers and to future you.",
  "The best backup is the one you tested.",
  "The best plan survives contact with the venue.",
  "The best cue is the one that lands.",
  "The best login is the one that works.",
  "Welcome back to the booth.",
  "Welcome back to the rack.",
  "Welcome back to the BOM.",
  "Welcome back to Mixinary.",
  "Places, please.",
  "Stand by…",
  "Go.",
];

export function pickLoginTagline(seed?: number): string {
  const i =
    seed !== undefined
      ? Math.abs(seed) % LOGIN_TAGLINES.length
      : Math.floor(Math.random() * LOGIN_TAGLINES.length);
  return LOGIN_TAGLINES[i] ?? LOGIN_TAGLINES[0];
}

export const LOGIN_TAGLINE_COUNT = LOGIN_TAGLINES.length;
