/** Pure role checks — re-exported from shared domain (web + iPad). */
export {
  canManageAdmin,
  canEditBom,
  canEditPricing,
  canManageProjects,
  canManageProcurement,
  canManageVendors,
  canManageClients,
  canReceive,
  canEditLabor,
  canApproveLabor,
  canEditExpenses,
  canApproveExpenses,
  canViewFinancials,
  canApproveChangeOrders,
  canEditBilling,
  canEditClientDocuments,
  canManageApAndSubs,
} from "@mixinary/domain";
