insert into public.carriers (name, slug) values
  ('UPS', 'ups'),
  ('USPS', 'usps'),
  ('FedEx', 'fedex'),
  ('DHL Express', 'dhl'),
  ('Amazon Logistics', 'amazon'),
  ('OnTrac', 'ontrac'),
  ('LaserShip', 'lasership'),
  ('Spee-Dee Delivery', 'spee-dee-delivery'),
  ('TForce Freight', 'tforce'),
  ('Lone Star Overnight', 'lone-star-overnight'),
  ('ABF Freight', 'abf-freight'),
  ('SEKO Logistics', 'seko-logistics'),
  ('Old Dominion Freight Line', 'old-dominion'),
  ('Estes Express Lines', 'estes'),
  ('FedEx Freight', 'fedex-freight'),
  ('UPS Freight', 'ups-freight'),
  ('SAIA LTL Freight', 'saia'),
  ('XPO Logistics', 'xpo-logistics'),
  ('R+L Carriers', 'rl-carriers'),
  ('Echo Global Logistics', 'echo-global');
